### PR TITLE
I just want to showcase that I built using jikanv4

### PR DESCRIPTION
**Pull request by benjoquilario**

### CODE REVIEW

**Comment by benjoquilario** [comment]
Hi, Jikan-me

I just want to showcase the website that I built using reactjs and jikanv4 api.
I wonder if it possible to add it on your [showcase](https://jikan.moe/showcase) web page

my repo: [https://github.com/benjoquilario/animehi](https://github.com/benjoquilario/animehi)

with best wishes

**Comment by irfan-dahir** [comment]
Hey, for sure! 

Could you please move it to the end of the list? Right above this:
```<a class="item add" href="https://github.com/jikan-me/website/edit/master/showcase.html" target="_blank"></a>```

I'll go ahead and merge this PR once that's done.

**Comment by benjoquilario** [comment]
Hi irfar-dan,

I've already done moving it right above this
`<a class="item add" href="https://github.com/jikan-me/website/edit/master/showcase.html" target="_blank"></a> 
`

**Comment by irfan-dahir** [comment]
Thanks!

**Pull request merged**
