### PR TITLE
Update showcase.html

### PR DESCRIPTION
**Pull request by VncntDzn**

### CODE REVIEW

**Comment by irfan-dahir** [comment]
Hey, thanks for the submission. 

New items are added at the end, can you please make that commit?

Thanks

**Comment by VncntDzn** [comment]
Hi Irfan!

Can I ask, how can I make the commit you're referring to?
Thanks

**Comment by irfan-dahir** [comment]
No worries, it's done. Refer to my commit.

**Comment by VncntDzn** [comment]
Awesome, thanks!

**Comment by VncntDzn** [comment]
Hi Irfan,

I would like to change my link's project. I already proposed it again. Let
me know if there are concerns. Thank you for consideration

**Pull request merged**
