### PR TITLE
add jikan4snek

### PR DESCRIPTION
**Pull request by sinkaroid**
- [x] I have read and accepted the [Rate-Limiting](https://docs.api.jikan.moe/#section/Information/Rate-Limiting) 
- [x] I have read and apply the [HTTP-Responses](https://docs.api.jikan.moe/#section/Information/HTTP-Responses) as well

Last night, you or other jikan sysadmin perhaps noticed that request from this useragent has ratelimited for several times, that actually right, I do plenty of bulk requests for testing case with jikan4snek.

We tried our best that user should have no worries with ratelimit, Jikan4SNEK combines cached and ratelimit hits to simulating the requests. You can check our testing cases [here](https://github.com/ScathachGrip/jikan4snek/actions/workflows/request_sequentially.yml)

It is still not completed yet, but already 80% covers to the v4 jikan, We haven't added `reviews`, `schedules`, `season`, `top`, and `watch` endpoint yet

### CODE REVIEW

**Comment by irfan-dahir** [comment]
Cool! Thanks for the submission.

**Comment by sinkaroid** [comment]
Hi, thanks.. eeee probably It's out of this PR's scope though,
 
Is 3 requests per seconds working as intended? the [document](https://docs.api.jikan.moe/#section/Information/Rate-Limiting) said 3. I already adding `1 sec` when it's hit on 3, and has conditions cache check around `<0.5 sec` here

with these two i can assume added around `1.5 sec`, but sometimes its not going well when reaching 20-30 requests, still throwing 429 for me, or maybe Github CI's internet network is too fast or somehow

**Comment by irfan-dahir** [comment]
It should be working - this is the active config I have on my end
3 requests / second + 2 burst
60 requests / minute + 2 burst

**Comment by sinkaroid** [comment]
I see, thanks for explaining👌

**Pull request merged**
