### PR TITLE
Nav menu

### LINKED ISSUE #1: [UX] Mobile Navigation issues
1. Opened nav stays opened if resized to outside it's viewport
2. Go to top if menu is opened. Some devices open the menu but you don't see it unless you scroll up.

### PR DESCRIPTION
**Pull request by JohnDinhCodes**
I refactored the html and css so I could fix #1 
I also added a hamburger icon for the mobile menu.
Everything works up until the screen size is 600px, might need to go back and add another media query for smaller devices.

### CODE REVIEW

**Comment by irfan-dahir** [comment]
That looks really sleek! thanks for the PR and fixing #1 !

What do you suggest we do to fix the mobile viewport?

**Comment by JohnDinhCodes** [comment]
Probably adding another media query and use a different layout for mobile. I can try to tackle that later today if that's alright :smile:

**Comment by JohnDinhCodes** [comment]
I changed breakpointC from 500px to 600px instead of creating a new media query for the new menu for the mobile view port. Let me know if there's anything you want me to change about the menu

**Comment by irfan-dahir** [comment]
Hey, looks better! The shadow seems to be over-powered

What do you think about this instead?
```css
box-shadow: 0px 5px 15px rgba(0,0,0,.25);
border-radius: 5px;
```

**Comment by JohnDinhCodes** [comment]
Looks good to me, I went ahead and updated those changes

**Comment by irfan-dahir** [comment]
Sorry for the late response. Looks great, thanks again!

**Pull request merged**
